<?php

namespace Yarunoka\Docgen;

/**
 * Renders declarations into the single reference page. Everything is sorted
 * explicitly (namespaces, then short names) so the same source always
 * produces byte-identical output, which the freshness check relies on.
 */
final class Renderer
{
    private const FRONTMATTER = <<<'MD'
        ---
        title: Reference
        description: The public classes, interfaces and enums of yarunoka/laravel, generated from their docblocks.
        sidebar:
          order: 2
        ---

        <!-- Generated by `composer docs:generate`. Edit the docblocks in src/, not this file. -->
        MD;

    /** @param list<ClassDoc> $docs */
    public function render(array $docs): string
    {
        $byNamespace = [];
        foreach ($docs as $doc) {
            $byNamespace[$doc->namespace][] = $doc;
        }
        // A parent namespace is a string prefix of its children, so a plain
        // sort puts it first
        ksort($byNamespace, SORT_STRING);

        $out = self::FRONTMATTER . "\n";
        foreach ($byNamespace as $namespace => $types) {
            usort($types, fn(ClassDoc $a, ClassDoc $b) => strcmp($a->shortName, $b->shortName));
            $out .= "\n## $namespace\n";
            foreach ($types as $type) {
                $out .= $this->typeSection($type);
            }
        }

        return $out;
    }

    private function typeSection(ClassDoc $doc): string
    {
        $out = "\n### {$doc->shortName}\n\n`{$this->declarationLine($doc)}`\n";

        if ($doc->docblock !== null && $doc->docblock->text !== '') {
            $out .= "\n{$doc->docblock->text}\n";
        }

        if ($doc->cases !== []) {
            $out .= "\n#### Cases\n\n";
            foreach ($doc->cases as $case) {
                $out .= "- `$case`\n";
            }
        }
        if ($doc->constants !== []) {
            $out .= "\n#### Constants\n\n";
            foreach ($doc->constants as $constant) {
                $out .= $this->memberLine($constant->name, $constant->docblock);
            }
        }
        if ($doc->properties !== []) {
            $out .= "\n#### Properties\n\n";
            foreach ($doc->properties as $property) {
                $label = ($property->type !== null ? "{$property->type} " : '') . "\${$property->name}";
                $out .= $this->memberLine($label, $property->docblock);
            }
        }
        if ($doc->methods !== []) {
            $out .= "\n#### Methods\n\n";
            foreach ($doc->methods as $method) {
                $out .= $this->memberLine($method->signature, $method->docblock);
            }
        }

        return $out;
    }

    private function declarationLine(ClassDoc $doc): string
    {
        $line = implode(' ', array_filter([
            $doc->isAbstract ? 'abstract' : null,
            $doc->isFinal ? 'final' : null,
            $doc->isReadonly ? 'readonly' : null,
            $doc->kind,
            $doc->shortName,
        ]));
        if ($doc->kind === 'enum' && $doc->backingType !== null) {
            $line .= ": {$doc->backingType}";
        }
        if ($doc->extends !== null) {
            $line .= " extends {$doc->extends}";
        }
        if ($doc->implements !== []) {
            $line .= ' implements ' . implode(', ', $doc->implements);
        }

        return $line;
    }

    private function memberLine(string $label, ?Docblock $docblock): string
    {
        $summary = $docblock->summary ?? '';

        return "- `$label`" . ($summary !== '' ? " — $summary" : '') . "\n";
    }
}
