<?php

namespace Yarunoka\Docgen\Tests;

use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;
use Yarunoka\Docgen\ClassDoc;
use Yarunoka\Docgen\Extractor;
use Yarunoka\Docgen\Renderer;

class RendererTest extends TestCase
{
    /** @return list<ClassDoc> */
    private function fixtureDocs(string ...$fixtures): array
    {
        $extractor = new Extractor();
        $docs = [];
        foreach ($fixtures as $fixture) {
            foreach ($extractor->extract(__DIR__ . '/fixtures/' . $fixture) as $doc) {
                $docs[] = $doc->publicSurface();
            }
        }

        return $docs;
    }

    #[Test]
    public function page_opens_with_exactly_the_three_required_frontmatter_keys(): void
    {
        $page = (new Renderer())->render($this->fixtureDocs('Widget.php', 'SorterInterface.php'));

        $this->assertStringStartsWith(
            "---\n"
            . "title: Reference\n"
            . "description: The public classes, interfaces and enums of yarunoka/laravel, generated from their docblocks.\n"
            . "sidebar:\n"
            . "  order: 2\n"
            . "---\n",
            $page,
        );
    }

    #[Test]
    public function page_carries_a_marker_against_hand_edits(): void
    {
        $page = (new Renderer())->render($this->fixtureDocs('Widget.php'));

        $this->assertStringContainsString('<!-- Generated by `composer docs:generate`.', $page);
    }

    #[Test]
    public function namespaces_become_chapters_sorted_with_parents_first(): void
    {
        $page = (new Renderer())->render($this->fixtureDocs('edge.php', 'Widget.php'));

        preg_match_all('/^## (.+)$/m', $page, $chapters);
        $this->assertSame(['Docgen\Fixtures', 'Docgen\Fixtures\Edge'], $chapters[1]);
    }

    #[Test]
    public function types_are_alphabetical_within_a_namespace(): void
    {
        $page = (new Renderer())->render($this->fixtureDocs('Widget.php', 'Color.php', 'SorterInterface.php'));

        preg_match_all('/^### (.+)$/m', $page, $types);
        $this->assertSame(['Color', 'SorterInterface', 'Widget'], $types[1]);
    }

    #[Test]
    public function declaration_lines_show_kind_modifiers_and_parent_types(): void
    {
        $page = (new Renderer())->render($this->fixtureDocs('Widget.php', 'Color.php', 'SorterInterface.php'));

        $this->assertStringContainsString('`final readonly class Widget implements Docgen\Fixtures\SorterInterface`', $page);
        $this->assertStringContainsString('`interface SorterInterface extends Countable`', $page);
        $this->assertStringContainsString('`enum Color: string`', $page);
    }

    #[Test]
    public function members_render_as_lists_with_their_summaries(): void
    {
        $page = (new Renderer())->render($this->fixtureDocs('Widget.php', 'Color.php'));

        $this->assertStringContainsString('- `compare(Widget $a, Widget $b): int` — Compares two widgets by weight.', $page);
        $this->assertStringContainsString('- `DEFAULT_LABEL` — The label used when none is given.', $page);
        $this->assertStringContainsString('- `?int $weight`', $page);
        $this->assertStringContainsString('- `Red`', $page);
    }

    #[Test]
    public function empty_member_sections_are_omitted(): void
    {
        $page = (new Renderer())->render($this->fixtureDocs('SorterInterface.php'));

        $this->assertStringNotContainsString('#### Constants', $page);
        $this->assertStringNotContainsString('#### Properties', $page);
        $this->assertStringContainsString('#### Methods', $page);
    }

    #[Test]
    public function class_docblock_prose_keeps_all_paragraphs(): void
    {
        $page = (new Renderer())->render($this->fixtureDocs('Widget.php'));

        $this->assertStringContainsString("A widget that sorts itself.\n\nWidgets exist only to exercise the extractor.", $page);
    }

    #[Test]
    public function output_is_deterministic_regardless_of_input_order(): void
    {
        $renderer = new Renderer();

        $forward = $renderer->render($this->fixtureDocs('Widget.php', 'Color.php', 'edge.php'));
        $reversed = $renderer->render($this->fixtureDocs('edge.php', 'Color.php', 'Widget.php'));

        $this->assertSame($forward, $reversed);
    }
}
